package:
  name: scripting
  version: "0.2.0"

source:
  path: ..

requirements:
  build:
    - setuptools
    - pip
    - python
    - pytest
  run:
    - python
    - pytest
    - six

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs model_metadata --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"
